-- Initial schema for The Undergrads dashboard/shop.
-- Safe to run on a new Supabase project.

create table if not exists public.activity_logs (
  id bigint generated always as identity primary key,
  action text not null,
  order_id bigint,
  details text,
  created_at timestamp with time zone default now()
);

create table if not exists public.batch_folders (
  id integer generated by default as identity primary key,
  name text not null unique,
  created_at timestamp without time zone default now()
);

create table if not exists public.batches (
  id integer generated by default as identity primary key,
  name text not null unique,
  created_at timestamp without time zone default now()
);

create table if not exists public.colors (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.designs (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now(),
  price numeric default 0,
  description text default '',
  image_url text default '',
  is_published boolean default false
);

create table if not exists public.orders (
  id bigint generated always as identity primary key,
  name text not null,
  phone text,
  facebook text,
  chapter text,
  address text,
  color text not null,
  size text not null,
  design text,
  payment_status text default 'pending',
  price numeric default 0,
  note text default '',
  status text default 'Pending',
  created_at timestamp with time zone default now(),
  defective_note text,
  deleted_at timestamp with time zone,
  is_defective boolean default false,
  is_deleted boolean default false,
  is_trashed boolean,
  user_id uuid references auth.users(id),
  product_id text,
  quantity text,
  landmark text,
  batch text,
  batch_folder text
);

create table if not exists public.shop_orders (
  id bigint generated by default as identity primary key,
  order_ref text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  customer_facebook text default '',
  customer_chapter text default '',
  payment_method text not null check (payment_method in ('gcash', 'cod')),
  payment_status text not null default 'pending',
  total_amount numeric not null default 0,
  created_at timestamp with time zone default now()
);

create table if not exists public.shop_order_items (
  id bigint generated by default as identity primary key,
  shop_order_id bigint not null references public.shop_orders(id),
  design_name text not null,
  color text not null,
  size text not null,
  quantity integer not null default 1,
  unit_price numeric not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.stocks (
  id bigint generated by default as identity primary key,
  color text not null,
  size text not null,
  quantity integer not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.trash_orders (
  id bigint generated always as identity primary key,
  name text not null,
  phone text,
  facebook text,
  chapter text,
  address text,
  color text not null,
  size text not null,
  design text,
  payment_status text default 'pending',
  price numeric default 0,
  note text default '',
  status text default 'Pending',
  created_at timestamp with time zone default now(),
  defective_note text default '',
  deleted_at timestamp with time zone default now(),
  is_defective boolean default false,
  is_deleted boolean default false,
  is_trashed boolean default false,
  batch_folder text,
  batch text
);

create index if not exists activity_logs_order_id_idx on public.activity_logs(order_id);
create index if not exists orders_created_at_idx on public.orders(created_at);
create index if not exists orders_batch_folder_idx on public.orders(batch_folder);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists shop_order_items_shop_order_id_idx on public.shop_order_items(shop_order_id);
create index if not exists stocks_color_size_idx on public.stocks(color, size);
create index if not exists trash_orders_deleted_at_idx on public.trash_orders(deleted_at);
